export declare enum ActionTypeEnum {
    CREATE = "CREATE",
    UPDATE = "UPDATE",
    DELETE = "DELETE"
}
export declare enum ErrorCode {
    INVALID_AUTH = "INVALID_AUTH",
    INVALID_INTENT = "INVALID_INTENT",
    INVALID_UNKNOWN_TRIGGER = "INVALID_UNKNOWN_TRIGGER",
    INVALID_AGENT = "INVALID_AGENT"
}
